# The Inroduction

## The essence of maps

Creating map is a useful way to take space into account in your research.
The common ways to explain why to do so are Tobler's laws of geography:

> - Everything is related to everything else, but near things are more related than distant things
> - The phenomenon external to an area of interest affects what goes on inside
> --- <cite>Waldo Tobler</cite>\

In fact, you shall not interpret these as strict laws of any kind. However it
is very useful to treat these statements as initial hypotheses for spatial data
analysis. In order to check whether any spatial pattern is or is not presented
in a phenomenon, you can apply different techniques. Exploratory data analysis
can be performed with spatial data, displaying a map is a way to visually evaluate
quantitative features of spatial distribution, spatial statistics is a set of
techniques to estimate qualitative features of spatial distribution. And our
course follows this order to undercover you exciting world of spatial data analysis.

- First lesson is a brief introduction to a domain
- In the second lesson we will talk about creating plots with spatial data and GeoDa
- The third is about creation of simple thematic maps with GeoDa
- The last three lessons are about spatial statistics applications


